/* Proposals operate only on explicit new-entry drafts, never persisted history. */
(function(){
  const names={person_id:'Titular económico',payer_person_id:'Pagador / cobrador',account_id:'Cuenta',counterparty_id:'Tercero',category_id:'Categoría',activity_project_id:'Actividad / proyecto',tag_ids:'Etiquetas',expense_scope:'Ámbito',type:'Tipo',concept:'Concepto',counterparty:'Nombre / alias del tercero',amount:'Importe'};
  const refs={person_id:'people',payer_person_id:'people',account_id:'accounts',counterparty_id:'counterparties',category_id:'categories',activity_project_id:'activity_projects',tag_ids:'tags'};
  const catalogs=()=>({people,accounts,categories,counterparties:window.domusCounterparties||[],activity_projects:window.domusLabels?.activities||[],tags:window.domusLabels?.tags||[]});
  const own=()=>Object.fromEntries(Object.entries(catalogs()).map(([k,v])=>[k,v.filter(x=>x.household_id===household.id)]));
  const el=id=>document.getElementById(id),esc=v=>escapeHtml(String(v??''));
  let accepted={},editing=null;const listening=new WeakSet();
  const enumValues={type:[['income','Ingreso'],['expense','Gasto']],expense_scope:[['domestic','Doméstico'],['business','Actividad económica'],['mixed','Mixto']]};
  function select(field,id,value,multiple=false){
    const selected=multiple?(value||[]):[value];
    const choices=refs[field]?(own()[refs[field]]||[]).filter(x=>x.active!==false||selected.includes(x.id)).map(x=>[x.id,(field==='category_id'?window.DOMUSClassification.categoryLabel(x):x.name)+(x.active===false?' (inactivo)':'')]):enumValues[field];
    return `<label for="${id}">${names[field]}</label><select id="${id}" ${multiple?'multiple size="4"':''}>${multiple?'':'<option value="">Sin condición / sin propuesta</option>'}${choices.map(([v,n])=>`<option value="${esc(v)}" ${selected.includes(v)?'selected':''}>${esc(n)}</option>`).join('')}</select>`;
  }
  async function requireSchema(){if(!navigator.onLine)throw Error('Las reglas requieren conexión para guardar.');const {data,error}=await sb.rpc('domus3_rules_version');if(error||data!==34)throw Error('Reglas pendientes de migración Alpha 34. No se ha guardado ningún cambio.');}
  function settings(){const box=el('classificationRuleList');if(!box)return;box.innerHTML=(!window.domusRulesReady?'<p>Reglas no disponibles sin conexión o sin migración Alpha 34.</p>':'')+(window.domusRules||[]).filter(x=>x.household_id===household.id).slice().sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id)).map(r=>`<div class="setting-row"><span>${esc(r.name)} · Prioridad ${r.priority} · ${r.active?'Activa':'Inactiva'} · Revisión ${r.revision}</span><div class="actions"><button class="btn" type="button" data-edit-rule="${esc(r.id)}">Editar / priorizar</button><button class="btn" type="button" data-toggle-rule="${esc(r.id)}">${r.active?'Desactivar':'Activar'}</button></div></div>`).join('');box.querySelectorAll('[data-edit-rule]').forEach(b=>b.onclick=()=>edit(b.dataset.editRule));box.querySelectorAll('[data-toggle-rule]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggleRule));}
  async function persist(row,id){await requireSchema();window.DOMUSClassification.validateRule(row,own());let q=sb.from('classification_rules');q=id?q.update({name:row.name,priority:row.priority,active:row.active,conditions:row.conditions,proposals:row.proposals}).eq('id',id).eq('household_id',household.id):q.insert(row);const {data,error}=await q.select('id').single();if(error)throw error;if(!data?.id)throw Error('Regla no disponible');await refreshAll();}
  async function toggle(id){const r=(window.domusRules||[]).find(x=>x.id===id&&x.household_id===household.id);if(!r)return;try{await persist({...r,active:!r.active},id)}catch(e){alert(e.message)}}
  function edit(id){editing=(window.domusRules||[]).find(x=>x.id===id&&x.household_id===household.id)||null;const r=editing||{name:'',priority:100,active:true,conditions:{},proposals:{}};let modal=el('ruleEditor');if(!modal){modal=document.createElement('div');modal.id='ruleEditor';modal.className='modal';document.body.append(modal)}
    modal.innerHTML=`<div class="modal-box" role="dialog" aria-modal="true" aria-label="Regla de clasificación" style="max-height:90vh;overflow:auto;background:white;padding:20px;border-radius:12px;width:min(680px,95vw)"><form id="ruleEditorForm"><h2>${editing?'Editar':'Nueva'} regla</h2><div class="draft-grid"><div class="field"><label for="ruleName">Nombre</label><input id="ruleName" required value="${esc(r.name)}"></div><div class="field"><label for="rulePriority">Prioridad (menor primero)</label><input id="rulePriority" type="number" step="1" required value="${r.priority}"></div><label><input id="ruleActive" type="checkbox" ${r.active?'checked':''}> Activa</label><h3 class="full">Condiciones · todas deben coincidir</h3>${['counterparty_id','account_id','type','person_id','payer_person_id'].map(f=>'<div class="field">'+select(f,'rc_'+f,r.conditions[f])+'</div>').join('')}<div class="field"><label for="rc_mode">Concepto</label><select id="rc_mode"><option value="contains">Contiene</option><option value="equals" ${r.conditions.concept?.mode==='equals'?'selected':''}>Coincide exactamente</option></select><input id="rc_text" aria-label="Texto del concepto" value="${esc(r.conditions.concept?.value)}"></div><div class="field"><label for="rc_min">Importe mínimo</label><input id="rc_min" type="number" min="0" step="0.01" value="${esc(r.conditions.amount?.min)}"><label for="rc_max">Importe máximo</label><input id="rc_max" type="number" min="0" step="0.01" value="${esc(r.conditions.amount?.max)}"></div><h3 class="full">Propuestas · vacío conserva el campo</h3>${['category_id','person_id','payer_person_id','counterparty_id','activity_project_id','tag_ids','expense_scope'].map(f=>'<div class="field">'+select(f,'rp_'+f,r.proposals[f],f==='tag_ids')+'</div>').join('')}</div><p id="ruleError" role="alert"></p><div class="actions"><button class="btn primary" type="submit">Guardar regla</button><button class="btn" type="button" id="ruleClose">Cerrar</button></div></form></div>`;
    modal.classList.add('show');el('ruleClose').onclick=()=>modal.classList.remove('show');el('ruleEditorForm').onsubmit=save;el('ruleName').focus();
  }
  async function save(e){e.preventDefault();const conditions={},proposals={};for(const f of ['counterparty_id','account_id','type','person_id','payer_person_id'])if(el('rc_'+f).value)conditions[f]=el('rc_'+f).value;if(el('rc_text').value.trim())conditions.concept={mode:el('rc_mode').value,value:el('rc_text').value.trim()};const amount={};for(const k of ['min','max'])if(el('rc_'+k).value!=='')amount[k]=Number(el('rc_'+k).value);if(Object.keys(amount).length)conditions.amount=amount;for(const f of ['category_id','person_id','payer_person_id','counterparty_id','activity_project_id','expense_scope'])if(el('rp_'+f).value)proposals[f]=el('rp_'+f).value;const tags=[...el('rp_tag_ids').selectedOptions].map(x=>x.value);if(tags.length)proposals.tag_ids=tags;const row={household_id:household.id,name:el('ruleName').value.trim(),priority:Number(el('rulePriority').value),active:el('ruleActive').checked,conditions,proposals};const button=e.submitter;button.disabled=true;try{await persist(row,editing?.id);el('ruleEditor').classList.remove('show')}catch(err){el('ruleError').textContent=err.message}finally{button.disabled=false}}
  function fields(key){const doc=key.startsWith('doc'),i=doc?key.slice(3):'',p=doc?'dd':'f';return Object.fromEntries(Object.entries({type:'Type',concept:'Concept',amount:'Amount',counterparty:'Counterparty',counterparty_id:'CounterpartyId',person_id:'Person',payer_person_id:'Payer',account_id:doc?'Account':'Bank',category_id:'Category',activity_project_id:'Activity',tag_ids:'Tags',expense_scope:doc?'Scope':'ExpenseScope'}).map(([k,v])=>[k,el(p+v+i)]));}
  function input(key){return {household_id:household.id,...Object.fromEntries(Object.entries(fields(key)).map(([k,e])=>[k,k==='tag_ids'?[...(e?.selectedOptions||[])].map(x=>x.value):e?.value||null]))}}
  function label(field,value){if(Array.isArray(value))return value.map(v=>label(field,v)).join(', ');return refs[field]?((row)=>row?(field==='category_id'?window.DOMUSClassification.categoryLabel(row):row.name):String(value))(own()[refs[field]].find(x=>x.id===value)):enumValues[field]?.find(x=>x[0]===value)?.[1]||String(value)}
  function reasonText(c){if(c.field==='concept')return (c.condition.mode==='contains'?'Contiene ':'Coincide con ')+c.condition.value+' · leído: '+c.observed;if(c.field==='amount')return [c.condition.min!=null?'≥ '+c.condition.min:'',c.condition.max!=null?'≤ '+c.condition.max:''].filter(Boolean).join(' y ')+' · leído: '+c.observed;return label(c.field,c.condition??c.observed)}
  function preview(key){if(key==='manual'&&el('editSeriesId').value)return;const panel=el('rulePreview_'+key);if(!panel)return;const result=window.DOMUSClassification.proposeRules(input(key),window.domusRules||[],own());const signature=JSON.stringify([result,accepted[key],window.domusRulesReady]);if(panel.dataset.signature===signature)return;panel.dataset.signature=signature;panel.innerHTML='<strong>Propuesta de clasificación · revisable</strong>'+(!window.domusRulesReady?'<p>Reglas no disponibles sin conexión o sin migración Alpha 34.</p>':'')+Object.entries(result.proposals).map(([f,v])=>`<p>${esc(names[f])}: <strong>${esc(label(f,v))}</strong> · ${result.explanation[f].map(r=>esc(r.name)+(r.id?' · revisión '+r.revision:'')+' ('+r.reasons.map(c=>esc(names[c.field]||c.field)+': '+esc(reasonText(c))).join('; ')+')').join(' / ')}</p>`).join('')+result.conflicts.map(c=>`<p role="alert">Revisión manual: ${esc(names[c.field])} tiene propuestas incompatibles con igual prioridad (${c.rules.map(r=>esc(r.name)+': '+esc(label(c.field,r.value))).join(', ')}). No se aplica este campo.</p>`).join('')+result.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+(!result.matches.length&&!Object.keys(result.proposals).length?'<p>Ninguna regla coincide.</p>':'')+(accepted[key]?'<p>Propuesta aplicada al borrador; puedes cambiar todos los campos antes de guardar.</p>':'')+(window.domusRulesReady&&Object.keys(result.proposals).length?'<button type="button" class="btn">Aplicar propuesta al borrador</button>':'');const button=panel.querySelector('button');if(button)button.onclick=()=>apply(key,result);}
  function apply(key,result){if(!window.domusRulesReady)return;result=window.DOMUSClassification.proposeRules(input(key),window.domusRules||[],own());if(key==='manual'&&el('editSeriesId').value)return;const f=fields(key);for(const [k,v] of Object.entries(result.proposals)){if(!f[k])continue;if(k==='tag_ids'){const tags=new Set([...f[k].selectedOptions].map(x=>x.value).concat(v));[...f[k].options].forEach(o=>o.selected=tags.has(o.value))}else f[k].value=v;}accepted[key]={household_id:household.id,at:new Date().toISOString(),input:result.input,proposals:result.proposals,explanation:result.explanation,conflicts:result.conflicts,applied:Object.fromEntries(Object.keys(result.proposals).map(k=>[k,input(key)[k]]))};if(key==='manual')syncPrefFields();else if(currentDocDrafts[Number(key.slice(3))])currentDocDrafts[Number(key.slice(3))].classification_review=accepted[key];preview(key);}
  function mount(key){delete accepted[key];const f=fields(key),parent=key==='manual'?el('movementForm'):f.concept?.closest('.draft-card');if(!parent)return;let panel=el('rulePreview_'+key);if(!panel){panel=document.createElement('div');panel.id='rulePreview_'+key;panel.className='msg info';parent.insertBefore(panel,[...parent.children].find(x=>x.classList.contains('form-actions')||x.classList.contains('actions'))||null)}panel.hidden=false;Object.values(f).forEach(e=>{if(e&&!listening.has(e)){listening.add(e);e.addEventListener('change',()=>preview(key));e.addEventListener('input',()=>preview(key))}});preview(key);}
  function hideManual(){delete accepted.manual;if(el('rulePreview_manual'))el('rulePreview_manual').hidden=true;}
  function reviewFields(key){if(key==='manual'&&el('editSeriesId').value)return {};return accepted[key]?.household_id===household.id?{classification_review:accepted[key]}:{}}
  function audit(row){const r=row.classification_review;if(!r||r.household_id!==household.id)return '';return '<details><summary>Propuesta revisada al crear</summary><p>Los valores actuales incluyen los cambios confirmados por el usuario.</p>'+Object.entries(r.explanation||{}).map(([f,rs])=>'<p>'+esc(names[f]||f)+': '+esc(label(f,r.proposals?.[f]))+' · '+(Array.isArray(rs)?rs:[]).map(x=>esc(x.name)+' · '+esc(x.id||'Maestro')+(x.revision?' · revisión '+esc(x.revision):'')+' · '+(x.reasons||[]).map(c=>esc(names[c.field]||c.field)+': '+esc(reasonText(c))).join('; ')).join(' / ')+'</p>').join('')+'</details>'}
  window.DOMUSRuleUI={audit,settings,edit,toggle,requireSchema,manual:()=>mount('manual'),hideManual,docs:d=>{accepted={};d.forEach((_,i)=>mount('doc'+i))},reviewFields};
})();
